-- QUESTION BANK & ASSESSMENT TABLES

DROP TABLE IF EXISTS student_answers CASCADE;
DROP TABLE IF EXISTS exam_questions CASCADE;
DROP TABLE IF EXISTS generated_exams CASCADE;
DROP TABLE IF EXISTS question_options CASCADE;
DROP TABLE IF EXISTS questions CASCADE;

DROP TABLE IF EXISTS question_types CASCADE;
DROP TABLE IF EXISTS question_difficulty_levels CASCADE;

-- AI & IMPACT TABLES

DROP TABLE IF EXISTS parent_actions CASCADE;
DROP TABLE IF EXISTS recommendations CASCADE;
DROP TABLE IF EXISTS ai_analysis_topics CASCADE;
DROP TABLE IF EXISTS student_ai_analysis CASCADE;

-- EDUCATIONAL DATA TABLES

DROP TABLE IF EXISTS attendance CASCADE;
DROP TABLE IF EXISTS grades CASCADE;

DROP TABLE IF EXISTS topics CASCADE;
DROP TABLE IF EXISTS subjects CASCADE;

DROP TABLE IF EXISTS student_parents CASCADE;
DROP TABLE IF EXISTS parents CASCADE;

DROP TABLE IF EXISTS students CASCADE;
DROP TABLE IF EXISTS classes CASCADE;
DROP TABLE IF EXISTS teachers CASCADE;
DROP TABLE IF EXISTS schools CASCADE;

-- ENUMS

DROP TYPE IF EXISTS exam_status CASCADE;
DROP TYPE IF EXISTS question_source CASCADE;

DROP TYPE IF EXISTS recommendation_status CASCADE;
DROP TYPE IF EXISTS topic_analysis_type CASCADE;
DROP TYPE IF EXISTS attendance_status CASCADE;
DROP TYPE IF EXISTS grade_type CASCADE;